apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: app
        image: {{ .Values.werf.image.bot }}
        env:
        - name: TELEGRAM_API_ID
          value: "{{ $.Values.bot.telegram.api_id }}"
        - name: TELEGRAM_API_HASH
          value: {{ $.Values.bot.telegram.api_hash }}
        - name: TELEGRAM_BOT_TOKEN
          value: {{ $.Values.bot.telegram.bot_token }}